### ISSUE TITLE
No Wire.endTransmission() needed after Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [sparkfun/SparkFun_ADXL345_Arduino_Library#5]
In the file "SparkFun_ADXL345.cpp", in the function "readFromI2C()", there is a Wire.endTransmission() after the Wire.requestFrom(). The Wire.endTransmission() should only be used when writing data, because the Wire.requestFrom() is a complete i2c session on its own.

**Comment by loricrotser** [comment]
Fixed.
